### ISSUE TITLE
Extract key listener

### ISSUE THREAD

**Issue by fregante** [karaggeorge/macos-key-cast#6]
It doesn't look like there's a reliable global keypress handler for Node. `iohook` [crashes](https://github.com/wilix-team/iohook/issues?q=is%3Aissue+is%3Aopen+label%3Amacos+) on macOS. I had to [use Electron just for that](https://github.com/fregante/marshall-multi-room/blob/59c8cc83b376b374744147e099026bf8681d0cf4/index.js#L33-L45).

Would it be possible to extract the keyboard listener component into its own npm module? Like `iohook` but just for macOS

Amazing little app by the way!

**Comment by karaggeorge** [comment]
Hey, the listener and the UI are both written in swift. All the node.js code does is call the binary with the right args. How would you expect the listener to work in Node.js? Some kind of event emitter?

**Comment by fregante** [comment]
Yes, however I realized that your library does not capture the pressed key, so its use might be further limited (still useful though!)
