### ISSUE TITLE
Use `␛` instead of `⎋`

### ISSUE THREAD

**Issue by fregante** [karaggeorge/macos-key-cast#7]
⎋ isn't very understandable and while it's used in some menus, it's not what's on the keyboard.

Could you change it to ␛?

# ␛ 

The above character is pretty small though.

---

Also I'm reporting a related bug:

![aa212](https://user-images.githubusercontent.com/1402241/99200021-97b16700-2768-11eb-92ec-a322c69516d5.gif)

Here's a gif of pressing `esc` a few times. You can see that after the first time it's smaller and even less understandable. 

macOS 10.15.7, US keyboard, let me know if you need any other information or if replacing the key would fix it.

**Comment by karuppiah7890** [comment]
Maybe this could be some sort of config. Then the user can choose. Then the question would be - what's the default 😅

**Comment by fregante** [comment]
I'm generally not a fan of configs, so I'd suggest to just use the most useful setting (`esc` for me)

If you want to implement further settings, perhaps you could make a "keymap", so users can also map `⌃` to the plain string `ctrl`

**Comment by karuppiah7890** [comment]
I get it. It's just that, it's hard to satisfy all users I guess. Hence the
suggestion
